- name: Clone frontend repo
  git:
    repo: "{{ app_repo_frontend }}"
    dest: /home/viktor/frontend
    version: main
    force: yes

- name: Start frontend Docker Compose
  shell: |
    cd /home/viktor/frontend &&
    docker compose down &&
    docker compose up -d --build
  args:
    executable: /bin/bash