- name: Pull postgres image
  docker_image:
    name: postgres
    tag: 17
    source: pull

- name: Start Postgres container
  docker_container:
    name: db
    image: postgres:17
    state: started
    restart_policy: unless-stopped
    env:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data